// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkWrqjFPG_6GIc9N8ydsuadGZWbG1or9Q',
    appId: '1:533662849776:web:4c93248e582ea4f9650035',
    messagingSenderId: '533662849776',
    projectId: 'marketlist-9290f',
    authDomain: 'marketlist-9290f.firebaseapp.com',
    storageBucket: 'marketlist-9290f.appspot.com',
    measurementId: 'G-K8VY0RJ05H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg1L5gnqyVZ7ok1-YThKY5cAByuT7iBds',
    appId: '1:533662849776:android:e8dd0f2ccbc9d2ea650035',
    messagingSenderId: '533662849776',
    projectId: 'marketlist-9290f',
    storageBucket: 'marketlist-9290f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyzMfCay56Gg86P13v9zxK0Ovd9t1r4WE',
    appId: '1:533662849776:ios:9843d7e4244765f9650035',
    messagingSenderId: '533662849776',
    projectId: 'marketlist-9290f',
    storageBucket: 'marketlist-9290f.appspot.com',
    iosClientId: '533662849776-vet7einb4ksfmccf144ki7eed4reb96b.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyzMfCay56Gg86P13v9zxK0Ovd9t1r4WE',
    appId: '1:533662849776:ios:31bc947f9c580a87650035',
    messagingSenderId: '533662849776',
    projectId: 'marketlist-9290f',
    storageBucket: 'marketlist-9290f.appspot.com',
    iosClientId: '533662849776-e5sh1odrmlq8ggjaivq8pah7p5htg034.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketListApp.RunnerTests',
  );
}
